SELECT 
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.IS_NULLABLE,
    c.DATA_TYPE
FROM 
    INFORMATION_SCHEMA.COLUMNS c
JOIN 
    INFORMATION_SCHEMA.TABLES t ON c.TABLE_NAME = t.TABLE_NAME
WHERE 
    t.TABLE_TYPE = 'BASE TABLE'
    -- 排除掉系统生成的迁移历史表，只看业务表
    AND t.TABLE_NAME <> '__EFMigrationsHistory'
ORDER BY 
    t.TABLE_NAME, c.ORDINAL_POSITION;